all:
  children:
    aurora_cloud:
      hosts:
        aurora-cloud:
          ansible_host: 130.246.212.116
          ansible_user: azimuth
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_jasmin_20200514
          ansible_ssh_common_args: "-J login"
